- .eslintrc.js
- package-lock.json
- package.json
- src/App.test.tsx
- src/libs/axios.ts
- src/resources/TagResource.ts
- src/routes/Namespaces/Repository/Repository.test.tsx
- src/routes/Namespaces/Repository/Repository.tsx
- src/routes/Namespaces/Repository/Tabs/Tags/Filter.tsx
- src/routes/Namespaces/Repository/Tabs/Tags/SecurityDetails.tsx
- src/routes/Namespaces/Repository/Tabs/Tags/Table.tsx
- src/routes/Namespaces/Repository/Tabs/Tags/Tags.test.tsx
- src/routes/Namespaces/Repository/Tabs/Tags/Tags.tsx
- yarn.lock
Adds the following:
- API calls to retrieve tags, manifests, and security status
- Tests for tag list components
> Adding API calls and tests to tag list

- README.md
- src/libs/axios.ts
- src/routes/NavigationPath.tsx
- src/routes/Organizations/Organizations.tsx
- src/routes/Organizations/Repositories/Repositories.tsx
- src/routes/StandaloneMain.tsx
- src/tests/fake-db/ApiMock.ts
- src/tests/fake-db/MockAxios.ts
- src/tests/fake-db/data/login/login.ts
- src/tests/fake-db/data/user/user.ts
API mock is enabled by setting `MOCK_API=true` before running `npm start`
> Add mock API for running UI without backend

- .env.development
- src/components/shared/Repository/Tabs/Tags/Table.tsx
- webpack.common.js
- webpack.dev.js
- webpack.prod.js
* Adds a `.env.development` file that can be used for exclusive dev env variables
* Updates docker pull commands to dynamically set domain
> Add dev env variables

- src/components/header/HeaderToolbar.tsx
- src/routes/Signin/Signin.tsx
Fixes on singin page:
* Remember me not needed
* Forgot password not needed
* Signup not needed
Fixes on the navbar: 
* User dropdown:  My profile not needed
* User dropdown:  Management not needed
* Notification, settings, help not needed
> remove unimplemented items from nav and login page

- src/components/labels/Labels.tsx
- src/resources/TagResource.ts
- src/routes/RepositoryDetails/Tags/Table.tsx
- src/routes/RepositoryDetails/Tags/Tags.tsx
- src/routes/TagDetails/Details/Details.tsx
- src/routes/TagDetails/TagDetails.test.tsx
- src/tests/fake-db/ApiMock.ts
- src/tests/fake-db/data/tag/labels.ts
Tag details page now loads associated tag labels. Includes refactor of the `src/routes/RepositoryDetails/Tags/Table.tsx` component.
> labels: View tag labels (PROJQUAY-4153)

- src/atoms/PackagesState.ts
- src/libs/utils.ts
- src/resources/TagResource.ts
- src/routes/NavigationPath.tsx
- src/routes/TagDetails/Packages/Packages.tsx
- src/routes/TagDetails/Packages/PackagesChart.tsx
- src/routes/TagDetails/Packages/PackagesFilter.tsx
- src/routes/TagDetails/Packages/PackagesTable.tsx
- src/routes/TagDetails/TagDetailsTabs.tsx
Adds packages tab to tag details
> Add packages tab to tag details

- src/routes/NavigationPath.tsx
- src/routes/RepositoryDetails/RepositoryDetails.test.tsx
- src/routes/RepositoryDetails/Tags/SecurityDetails.tsx
- src/routes/RepositoryDetails/Tags/Table.tsx
- src/routes/RepositoryDetails/Tags/Tags.test.tsx
- src/routes/RepositoryDetails/Tags/Tags.tsx
- src/routes/StandaloneMain.tsx
- src/routes/TagDetails/Details/Details.tsx
- src/routes/TagDetails/TagDetails.test.tsx
- src/routes/TagDetails/TagDetailsTabs.tsx
- src/routes/TagDetails/Types.ts
Adds preview security report in the repo and tag details pages.
The TagDetailsTabs and NavigationPath files have been refactored to remove circular imports.
> security: Add security preview (PROJQUAY-4171)

- src/routes/OrganizationsList/CreateOrganizationModal.tsx
- src/routes/OrganizationsList/OrganizationsList.tsx
- src/routes/OrganizationsList/css/Organizations.scss
> fix slider in create org modal

- src/routes/TagDetails/SecurityReport/SecurityReportChart.tsx
- src/tests/fake-db/data/repository/security.ts
> Fix security report chart for no vulns

- src/components/modals/CreateRepoModalTemplate.tsx
> Add user namespace to create repo modal

- src/routes/OrganizationsList/CreateOrganizationModal.tsx
- src/routes/OrganizationsList/OrganizationsList.tsx
> Remove plans from create org modal

- src/routes/OrganizationsList/Organization/Organization.tsx
- src/routes/OrganizationsList/OrganizationsList.tsx
The PR fixes Hide Extra Tabs in Repos (PROJQUAY-4093) and Removes Grey Background and card styling from Org Page (PROJQUAY-4086)
> Utils: Removing Usage Logs tab in RepositoriesList Page and Removing grey background from Organizations Page

- src/components/header/HeaderToolbar.css
- src/components/header/HeaderToolbar.tsx
- src/components/header/QuayHeaderToolbar.css
- src/index.tsx
* Adds switch to toolbar for toggling between old and new ui
> Add switch to toolbar (PROJQUAY-4124)

- .env.development
- Dockerfile
- src/libs/axios.ts
* Resolves issue with dev not loading due to axios protocol error
> Configure dev to use localhost:8080 and prod to use protocol + host

- src/components/modals/BulkDeleteModalTemplate.tsx
- src/routes/RepositoriesList/RepositoriesList.tsx
Fixes the column name of bulk delete from repo list and search of repo names
> fix bulk delete modal search and list repos (PROJQUAY-4329)

- src/components/modals/CreateRepoModalTemplate.tsx
> Add a / in the create repo modal (PROJQUAY-4355)

- src/atoms/UserState.ts
- src/components/modals/CreateRepoModalTemplate.tsx
- src/libs/utils.ts
- src/resources/MembersResource.ts
- src/resources/OrganizationResource.ts
- src/resources/RepositoryResource.ts
- src/resources/RobotsResource.ts
- src/resources/UserResource.ts
- src/routes/OrganizationsList/CreateOrganizationModal.tsx
- src/routes/OrganizationsList/OrganizationsList.tsx
- src/routes/RepositoriesList/RepositoriesList.tsx
- src/routes/StandaloneMain.tsx
- src/tests/fake-db/ApiMock.ts
- src/tests/fake-db/data/organization/members.ts
- src/tests/fake-db/data/organization/organization.ts
- src/tests/fake-db/data/organization/robots.ts
> Replace mock columns from org table with new valid columns (PROJQUAY-4082)

- src/resources/RobotsResource.ts
- src/routes/OrganizationsList/OrganizationsList.tsx
- src/tests/fake-db/ApiMock.ts
- src/tests/fake-db/data/user/robots.ts
> Add user robots count to org list table

- src/App.css
- src/components/toolbar/Pagination.tsx
- src/routes/OrganizationsList/OrganizationsList.tsx
- src/routes/RepositoriesList/RepositoriesList.tsx
- src/routes/RepositoryDetails/Tags/Tags.tsx
- src/routes/RepositoryDetails/Tags/TagsToolbar.tsx
> Adding Bottom Pagination to all Table component Views

- src/components/modals/CreateRepoModalTemplate.tsx
> Disable create repo on invalid input (PROJQUAY-4355)

- src/routes/RepositoryDetails/Tags/SecurityDetails.tsx
- src/tests/fake-db/data/repository/security.ts
> Fix alignment of vulnerability counts (PROJQUAY-4335)

- src/components/modals/BulkDeleteModalTemplate.tsx
- src/components/toolbar/ToolbarPagination.tsx
- src/routes/OrganizationsList/OrganizationToolBar.tsx
- src/routes/OrganizationsList/OrganizationsList.tsx
- src/routes/RepositoriesList/RepositoriesList.tsx
- src/routes/RepositoriesList/RepositoryToolBar.tsx
- src/routes/RepositoryDetails/Tags/Tags.tsx
- src/routes/RepositoryDetails/Tags/TagsToolbar.tsx
- src/tests/fake-db/data/organization/organization.ts
- src/tests/fake-db/data/user/robots.ts
- src/tests/fake-db/data/user/user.ts
> Add top pagination to bulk delete modal (PROJQUAY-4354)

- src/resources/OrganizationResource.ts
- src/resources/UserResource.ts
- src/routes/OrganizationsList/OrganizationsList.tsx
- src/tests/fake-db/data/config/config.ts
- src/tests/fake-db/data/organization/organization.ts
- src/tests/fake-db/data/user/user.ts
Populates organization list with all organizations when the superuser has full access. Requires API changes from this related PR: https://github.com/kleesc/quay/pull/2.
> Giving super access to all organizations (PROJQUAY-4456)

- src/routes/OrganizationsList/OrganizationsList.tsx
* Disables sorting by last modified
* Drastically improves org list performance by first rendering based on org names
> Add skeletons for Org list (PROJQUAY-4443)

- src/routes/RepositoriesList/RepositoriesList.tsx
Removes unused `set team permissions` option.
> Remove set team permissions option

- src/components/labels/Labels.css
- src/components/labels/Labels.tsx
- src/routes/TagDetails/Details/Details.css
- src/routes/TagDetails/Details/Details.tsx
- src/routes/TagDetails/Details/DetailsCopyTags.tsx
- src/routes/TagDetails/Packages/PackagesTable.tsx
- src/routes/TagDetails/SecurityReport/SecurityReportTable.tsx
- src/routes/TagDetails/TagDetails.tsx
A series of small CSS changes.
> Minor CSS changes (PROJQUAY-4352)

- src/routes/OrganizationsList/OrganizationsList.tsx
- src/routes/OrganizationsList/OrganizationsListTableData.tsx
* Loads data that's visible on Organizations page asynchronously.
> Add lazy loading (PROJQUAY-4463)

- src/atoms/TagListState.ts
- src/routes/OrganizationsList/OrganizationsList.tsx
- src/routes/RepositoriesList/RepositoriesList.tsx
- src/routes/RepositoryDetails/Tags/Tags.tsx
Pagination should use the filtered list, not the full list.
> Fixing pagination when filtering

- src/routes/OrganizationsList/CreateOrganizationModal.tsx
Adding validation that org name must be valid before submitting form. Adds alert icon to invalid orgname. Does not display message since format requirements are already present under input.
> Adding check on organization name

- src/routes/OrganizationsList/OrganizationsListTableData.tsx
* Resolves regression where skeleton renders for member count and team count columns for user orgs
> Fix for user namespace columns

- src/components/modals/CreateRepoModalTemplate.tsx
> Validation for Repository name

- src/resources/RepositoryResource.ts
- src/routes/RepositoryDetails/Tags/DeleteModal.tsx
- src/routes/RepositoryDetails/Tags/Tags.css
- src/routes/RepositoryDetails/Tags/Tags.tsx
- src/routes/RepositoryDetails/Tags/TagsToolbar.tsx
> Disabling delete tags if repo is in readonly state (PROJQUAY-4514)

- src/resources/RepositoryResource.ts
API call previously wasn't returning public repositories.
> Adding public repos to API call (PROJQUAY-4531)

- src/atoms/TagListState.ts
- src/routes/OrganizationsList/OrganizationsList.tsx
- src/routes/RepositoriesList/RepositoriesList.tsx
Fix search query input text length
Signed-off-by: harishsurf <hgovinda@redhat.com>
> Fix search query input text length - PROJQUAY-4525

- src/routes/OrganizationsList/CreateOrganizationModal.tsx
Previous Quay UI had additional warnings when trying to create and organization. The conditions are:
Condition `invalid org name` displays error `Must be alphanumeric, all lowercase, at least 2 characters long and at most 255 characters long`.
Condition `name less than 4 or more than 30` displays warning `Namespaces less than 4 or more than 30 characters are only compatible with Docker 1.6+`.
Condition `name contains dashes or dots` displays warning `Namespaces with dashes or dots are only compatible with Docker 1.9+`.
> Adding warnings to create org modal (PROJQUAY-4511)

- src/components/Table/RepoCount.tsx
- src/components/modals/BulkDeleteModalTemplate.tsx
- src/routes/OrganizationsList/OrganizationsList.tsx
Displays repo count on organization delete modal.
> Displaying number of repositories on organization delete modal

- cypress.config.ts
- cypress/e2e/packages-report.cy.ts
- cypress/e2e/repositories-list.cy.ts
- cypress/e2e/repository-details.cy.ts
- cypress/e2e/security-report.cy.ts
- cypress/e2e/signin.cy.ts
- cypress/e2e/tag-details.cy.ts
- src/components/modals/BulkDeleteModalTemplate.tsx
- src/components/modals/CreateRepoModalTemplate.tsx
- src/routes/RepositoriesList/RepositoriesList.tsx
- src/routes/RepositoryDetails/Tags/TablePopover.tsx
- src/routes/TagDetails/Details/Details.tsx
- src/routes/TagDetails/Details/DetailsCopyTags.tsx
- src/routes/TagDetails/Packages/PackagesChart.tsx
- src/routes/TagDetails/Packages/PackagesTable.tsx
- src/routes/TagDetails/SecurityReport/SecurityReportChart.tsx
- src/routes/TagDetails/SecurityReport/SecurityReportFilter.tsx
- src/routes/TagDetails/SecurityReport/SecurityReportTable.tsx
- src/tests/fake-db/ApiMock.ts
- src/tests/fake-db/data/repository/repository.ts
- src/tests/fake-db/data/repository/security.ts
- src/tests/fake-db/data/tag/manifest.ts
- src/tests/fake-db/data/tag/tag.ts
- src/tests/fake-db/data/user/user.ts
- tsconfig.json
Adds Cypress tests for the following pages:
- Repository detail
- Tag details
- Security report
- Packages report
- Repository list
> Adding additional integration tests

- package-lock.json
- package.json
* Resolves issue during downstream build
```
2022-11-02 15:46:23,908 - atomic_reactor.tasks.binary_container_build - INFO - > quay-ui@0.1.0 prepare
2022-11-02 15:46:23,908 - atomic_reactor.tasks.binary_container_build - INFO - > husky install
2022-11-02 15:46:23,908 - atomic_reactor.tasks.binary_container_build - INFO - 
2022-11-02 15:46:23,998 - atomic_reactor.tasks.binary_container_build - INFO - /tmp/prepare-4d60be97.sh: line 1: husky: command not found
```
> Move husky to optional deps

- cypress/e2e/packages-report.cy.ts
- cypress/e2e/security-report.cy.ts
- src/routes/TagDetails/Packages/Packages.tsx
- src/routes/TagDetails/SecurityReport/SecurityReport.tsx
- src/routes/TagDetails/SecurityReport/SecurityReportScanStates.tsx
Renders in the security and package reports depending on state of the security scan.
> Adding scan state components

- .github/workflows/ci.yml
- cypress/e2e/repositories-list.cy.ts
- src/libs/utils.ts
> Fix date format (PROJQUAY-4696)

- cypress/e2e/org-list.cy.ts
- cypress/e2e/repositories-list.cy.ts
- cypress/e2e/repository-details.cy.ts
- cypress/test/quay-db-data.txt
- src/components/modals/BulkDeleteModalTemplate.tsx
- src/components/modals/CreateRepoModalTemplate.tsx
- src/components/toolbar/ToolbarButton.tsx
- src/routes/OrganizationsList/CreateOrganizationModal.tsx
- src/routes/OrganizationsList/OrganizationToolBar.tsx
- src/routes/OrganizationsList/OrganizationsList.tsx
- src/routes/RepositoriesList/RepositoryToolBar.tsx
- src/routes/RepositoryDetails/Tags/Table.tsx
- src/tests/fake-db/data/organization/organization.ts
> e2e org page test

- src/routes/StandaloneMain.tsx
Adds the following banner to the top of the UI:
> Adding banner with review form

- cypress/e2e/repositories-list.cy.ts
- cypress/e2e/repository-permissions.cy.ts
- cypress/test/quay-db-data.txt
Separating adding of test data here. This PR is a pre-requisite for - https://github.com/quay/quay-ui/pull/164
> Adding 150 repositories for projectquay org in test data 

- cypress/e2e/repository-notifications.cy.ts
- src/components/ReadonlySecret.tsx
- src/routes/RepositoryDetails/Settings/Notifications.tsx
Adds configuration details to the notifications table.
> Adding notification details to list
