server.js
src/components/shared/Repository/Tabs/Tags/Table.tsx
src/components/shared/Repository/Tabs/Tags/Tags.test.tsx
src/resources/TagResource.ts
src/routes/NavigationPath.tsx
src/routes/StandaloneMain.tsx
src/routes/TagDetails/Details.tsx
src/routes/TagDetails/DetailsCopyTags.tsx
src/routes/TagDetails/TagDetails.test.tsx
src/routes/TagDetails/TagDetails.tsx
src/routes/TagDetails/TagDetailsArchSelect.tsx
src/routes/TagDetails/TagDetailsTabs.tsx
src/tests/fake-db/ApiMock.ts
src/tests/fake-db/data/security/security.ts
src/tests/fake-db/data/tag/manifest.ts
src/tests/fake-db/data/tag/tag.ts

Made the following changes:
- Added page to view details about a particular tag
- Manifest list tags can switch between architectures
- Taglist table now links to tag detailspage
- TagResource now accepts specificName parameter to get details for a single tag
- NavigationPath now has helper methods for getting domain and constructing tagdetails path
Running locally:
Run with `MOCK_API=true npm start` and go to the `organizations/testorg/testrepo` page. Selecting a tag there will go to the tag details page.

tagdetails: View details of a tag (PROJQUAY-3545)

---

src/routes/RepositoriesList/RepositoriesList.tsx

When going to a repo from the `Repositories` sidebar the URL is not correctly updated causing tag list to fail

Fix link when navigating from repo list to a repo

---

package-lock.json
package.json
webpack.config.ts
webpack.prod.js

* Removes `console.log` and `console.debug` from prod builds
This can be validated by building and running the local production build in a docker container and checking the console at signin:
```
docker build -t quay-ui:local .
docker run -d --name quay-ui -p 9000:9000 quay-ui:local
```
Old:
New:

Automatically remove console.*  (PROJQUAY-4195)

---

src/routes/RepositoriesList/RepositoriesList.tsx
src/routes/RepositoryDetails/Tags/SecurityDetails.tsx
src/routes/RepositoryDetails/Tags/Table.tsx
src/routes/TagDetails/Details/Details.tsx
src/routes/TagDetails/Packages/Packages.tsx
src/routes/TagDetails/SecurityReport/SecurityReport.tsx
src/routes/TagDetails/SecurityReport/SecurityReportChart.tsx
src/routes/TagDetails/SecurityReport/SecurityReportTable.tsx
src/routes/TagDetails/TagDetails.tsx

* Adds Spinners to tables to indicate loading
* Adds Skeleton to Tag table cells to indicate loading
* Adds Skeleton to Tag Details and Security Report pages. 
This can best be tested by throttling the network connection using either Firefox and [GPRS throttling](https://firefox-source-docs.mozilla.org/devtools-user/network_monitor/throttling/index.html) or Chrome and [url-throttler](https://chrome.google.com/webstore/detail/url-throttler/kpkeghonflnkockcnaegmphgdldfnden)

Use loading page while waiting on security report (PROJQUAY-4152)

---

src/atoms/SecurityDetailsState.ts
src/routes/RepositoryDetails/Tags/SecurityDetails.tsx
src/routes/RepositoryDetails/Tags/Table.tsx
src/routes/TagDetails/Packages/Packages.tsx
src/routes/TagDetails/Packages/PackagesChart.tsx
src/routes/TagDetails/Packages/PackagesTable.tsx
src/routes/TagDetails/SecurityReport/SecurityReport.tsx
src/routes/TagDetails/SecurityReport/SecurityReportChart.tsx
src/routes/TagDetails/SecurityReport/SecurityReportTable.tsx
webpack.config.ts
webpack.dev.js

* Fixes issue reloading pages locally that contained a tag with a `.` in the name
* Adds skeletons for Packages page [PROJQUAY-4243](https://issues.redhat.com/browse/PROJQUAY-4243)
* Handles security vulnerability timeouts on Tags page [PROJQUAY-4245](https://issues.redhat.com/browse/PROJQUAY-4245)
* Updates how unique table identifiers are calculated, makes them a little more unique
* Updates all Tag tabs to handle skeletons for three states: success, failure, pending

Add skeleton to packages page (PROJQUAY-4243)

---

package-lock.json
package.json
src/atoms/BrowserHistoryState.ts
src/components/breadcrumb/Breadcrumb.tsx
src/routes/NavigationPath.tsx
src/routes/OrganizationsList/OrganizationsList.tsx
src/routes/RepositoriesList/RepositoriesList.tsx
src/routes/TagDetails/TagDetails.tsx

Breadcrumbs are generated by two ways:
1. From url route
2. From Browser history
If the browser history is empty, breadcrumbs will be generated from the url route. If browser history exists, breadcrumbs are generated from this history. `BrowserHistoryState` tracks users history on the application.

Building Breadcrumbs by keeping track of browser history (PROJQUAY-4090)

---

src/components/LoadingPage.tsx
src/components/errors/ErrorModal.tsx
src/components/errors/SiteUnavailableError.tsx
src/components/header/HeaderToolbar.tsx
src/components/modals/BulkDeleteModalTemplate.tsx
src/components/modals/CreateRepoModalTemplate.tsx
src/resources/ErrorHandling.ts
src/resources/OrganisationResource.ts
src/resources/RepositoryResource.ts
src/resources/TagResource.ts
src/routes/OrganizationsList/CreateOrganizationModal.tsx
src/routes/OrganizationsList/OrganizationsList.tsx
src/routes/RepositoriesList/RepositoriesList.tsx
src/routes/RepositoryDetails/Tags/DeleteModal.tsx
src/routes/RepositoryDetails/Tags/Tags.tsx
src/routes/Signin/Signin.tsx
src/routes/StandaloneMain.tsx

Implements the following changes:
- React suspense moved to respository and orgnazation components, fixes choppy reload of screen
- Support for catching individual errors during bulk deletion
- Adding detail to user facing error messages
**Testing**
The mock API cannot be used to properly test errors since it does not return a real `AxiosError`. Editing the Quay backend to return 500 (`return "", 500`) for the relevant endpoints or shutting down the backend completely allows for more accurate errors.

errors: User facing formatting (PROJQUAY-4378)

---

src/routes/RepositoryDetails/Tags/TablePopover.tsx

uses quay config to set the correct domain

use QuayConfig to render the domain for fetch tags popover (PROJQUAY-4340)

---

src/components/toolbar/Kebab.tsx
src/routes/OrganizationsList/OrganizationsList.tsx

Fixes: [Selections still active, after navigation to new area](https://issues.redhat.com/browse/PROJQUAY-4349) and [In multi-select, replace ellipsis with text "More Actions"](https://issues.redhat.com/browse/PROJQUAY-4342)

Changing Ellipsis to More Actions button (PROJQUAY-4342)

---

src/resources/ErrorHandling.ts
src/routes/RepositoriesList/RepositoriesList.tsx
src/routes/RepositoryDetails/Tags/Tags.tsx
src/routes/TagDetails/Packages/Packages.tsx
src/routes/TagDetails/SecurityReport/SecurityReport.tsx
src/routes/TagDetails/TagDetails.tsx
src/routes/TagDetails/TagDetailsTabs.tsx

Refactoring error handling to surface resource not found errors for non existent tags and repositories. 
Currently does not handle organizations not found due to more API call's being required.

errors: Surface not found issues (PROJQUAY-4386)

---

src/components/header/HeaderToolbar.tsx

This is the first part of a two part PR. Second PR needs to be opened in quay repo to allow nginx to pass query args. 
* Prevents browser from caching nginx redirect to `/` by passing query args in replace request.

Fix browser caching / redirect (PROJQUAY-4423)

---

src/atoms/OrganizationListState.ts
src/atoms/RepositoryState.ts
src/atoms/UserState.ts
src/components/LoadingPage.tsx
src/components/errors/RequestError.tsx
src/components/modals/ConfirmationModal.tsx
src/components/modals/CreateRepoModalTemplate.tsx
src/hooks/UseRefreshPage.ts
src/hooks/UseRefreshUser.ts
src/routes/OrganizationsList/CreateOrganizationModal.tsx
src/routes/OrganizationsList/OrganizationsList.tsx
src/routes/RepositoriesList/RepositoriesList.tsx

We currently pull `UserState` via a recoil selector. This raises the following issues:
- Async recoil selectors are required to be idempotent, they cache responses based on the parameters passed in. This means you cannot get the latest values unless completely reloading the page. 
- The function recoil recommends for invalidating that cache is currently marked as `UNSTABLE`.
- We currently use the other method for invalidating the cache, adding another atom to the UserState selector. By updating the atom it invalidates the cache, retries the request, and re-renders all components dependent on UserState. This is error prone and somewhat complicated.
- Handling loading and error states using async recoil selectors differs from requests made directly in the component. Recoil requires using …

Refactoring organization and repository list pages

---

src/routes/OrganizationsList/OrganizationsList.tsx

Prevents race condition of loading organizations before the quay config has been loaded. Also includes request for config as apart of error handling since it's required for loading organizations.

Having org list loading depend on quay config

---

src/components/errors/404.tsx
src/routes/StandaloneMain.tsx

Currently paths with no matching route render an empty page. This defaults on non matching routes to render a 404 page. 
**How to test**
- All valid paths must render existing components
- Any non-matching paths should render the 404 page

Adding 404 default path

---

src/routes/Signin/Signin.tsx

**Text and logo should be aligned left**
[**Patternfly Login Page**
](https://www.patternfly.org/v4/components/login-page)
Before/currently as of 9/30 18:35 (text and logo centered)

Fixed alignment of logo

---

src/components/toolbar/DropdownCheckbox.tsx

Selecting all then selecting only what's on the current page will now show the correct value.

Fixing select all on page (PROJQUAY-4521)

---

src/components/Table/ImageSize.tsx
src/resources/TagResource.ts
src/routes/RepositoryDetails/Tags/SecurityDetails.tsx
src/routes/RepositoryDetails/Tags/Table.tsx
src/routes/TagDetails/Details/Details.tsx
src/routes/TagDetails/TagDetails.tsx
src/routes/TagDetails/TagDetailsArchSelect.tsx
src/routes/TagDetails/TagDetailsTabs.tsx

Makes the following changes:
- Size for child manifests are now computed correctly, by adding up the sizes of each layer
- Requests to security endpoint now pass the child digest instead of the parent digest to get the correct information
- Images with size `0` are displayed as unsupported. (Matches behavior of the old UI)
- Manifests with no features are displayed as unsupported. (Matches behavior of old UI)
- Architecture selection now displays operating system + architecture in dropdown
- Architecture selection value is tracked using digest since that is the unique value for the selected manifest
How to test
- Pull and run code locally. 
- Skopeo copy the `aspnet` image:
`skopeo copy docker://mcr.microsoft.com/dotnet/aspnet docker://localhost:8080/user/aspnet --all …

Fixing size computation, refactor architecture select (PROJQUAY-4532)

---

src/routes/RepositoryDetails/Tags/SecurityDetails.tsx
src/routes/TagDetails/Details/Details.tsx
src/routes/TagDetails/TagDetails.tsx

Fixes behavior for:
- When clicking `Vulnerabilities` section in the Tag Details page the security data state would be cleared causing the security report to render the loading screen that would never disappear. 
- When tag list was being loaded the recoil state for security data would be written to with each response but the information would never be read from. 
This PR causes the security state to be reset when the Tag Details page loads.

Fix security report loading error

---

src/resources/OrganizationResource.ts
src/routes/OrganizationsList/OrganizationsList.tsx

Deletion failed when using superuser because it called the wrong org deletion endpoint. This change uses the superuser delete org endpoint when logged in as a superuser and `FEATURE_SUPERUSERS_FULL_ACCESS: true`.

Org deletion now uses superuser endpoint

---

.github/workflows/ci.yml
.gitignore
README.md
cypress.config.ts
cypress/e2e/signin.cy.ts
cypress/fixtures/example.json
cypress/support/commands.ts
cypress/support/e2e.ts
package-lock.json
package.json

Uses Cypress to implement integration tests as a CI step. Here we're defining integration tests as `Tests that simulate end user interaction across components`.
Tests are implemented under `/cypress/e2e` and simulate user interaction with pages and assert on their behavior. The CI job goes through the following workflow.
- Install deps with `npm ci`
- Build the application to the `/dist` folder with `MOCK_API: true`: `npm run build`
- Serve the application with the `serve` npm package: `npm run start:integration`
- Run the tests with `npx cypress run`

Adding Cypress integration tests

---

package.json

* Required for downstream builds that do not use Cypress

Moves cypress optional

---

.github/workflows/ci.yml

- This PR changes the Github action to use the quay:latest image instead of building an image from source.

ci: Use custom image in ci docker-compose instead of building from source
